# Generated by Django 3.2.11 on 2022-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eBrochure',
        ),
    ]
