# Generated by Django 3.2.11 on 2022-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snable_saas', '0002_delete_ebrochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('docs', models.FileField(upload_to='book/docs')),
            ],
        ),
    ]
