# Generated by Django 3.2.11 on 2022-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0004_contact_genral_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_training_hiring_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField(max_length=10)),
                ('whatsapp_number', models.BigIntegerField(max_length=10)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
