# Generated by Django 3.2.11 on 2022-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0005_contact_training_hiring_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_genral_form',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact_genral_form',
            name='whatsapp_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact_training_hiring_form',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact_training_hiring_form',
            name='whatsapp_number',
            field=models.BigIntegerField(),
        ),
    ]
