# Generated by Django 3.2.11 on 2022-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0008_auto_20220421_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_genral_form',
            name='services',
            field=models.IntegerField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='contact_genral_form',
            name='sub_services',
            field=models.IntegerField(default=None, max_length=5),
        ),
    ]
