# Generated by Django 3.2.11 on 2022-04-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0016_remove_comments_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
