# Generated by Django 4.0.4 on 2022-05-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0018_blogcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
