# Generated by Django 4.0.4 on 2022-05-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0021_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=20),
        ),
    ]
