# Generated by Django 4.0.4 on 2022-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0024_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('position_applied_for', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_cv', models.FileField(upload_to='book')),
            ],
        ),
    ]
